version: "3.9"

services: 
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment: 
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=ngcash'
    volumes:
      - pg-data:/var/lib/postgresql/data
    container_name: db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@admin.com'
      - 'PGADMIN_DEFAULT_PASSWORD=2507'
    ports:
      - 5050:80
    depends_on:
      - db
    container_name: pgadmin

  api:
    build: 
      dockerfile: Dockerfile
      context: './server'
    ports:
      - 5000:5000
    volumes:
      - ./server:/ngcash/server  
      - /ngcash/server/node_modules/
    environment:
      - WATCHPACK_POLLING=true 
    depends_on:
      - db
    container_name: api
    

  app:
    build: 
      dockerfile: Dockerfile
      context: './front'
    volumes: 
      - ./front:/ngcash/app
      - /ngcash/app/node_modules/
    ports:
      - 3000:3000
    command: npm start
    environment:
      - WATCHPACK_POLLING=true  
    depends_on:
      - api
    container_name: app

volumes:
  pg-data:
  
  